<script setup>
import { ref, computed, watch } from 'vue'
import { useRoute } from 'vue-router'
import { portalApi } from '../api/portal.js'
import AppIcon from '../components/AppIcon.vue'
import LoadingState from '../components/LoadingState.vue'
import EmptyState from '../components/EmptyState.vue'
import ResourceLibraryView from './ResourceLibraryView.vue'
const props=defineProps({topics:Boolean}),route=useRoute(),items=ref([]),detail=ref(null),loading=ref(false),error=ref(''),keyword=ref('')
const base=computed(()=>props.topics?'/ideological-topics':'/course-resources'),filtered=computed(()=>items.value.filter(x=>(x.name+(x.code||'')+(x.description||'')).toLowerCase().includes(keyword.value.trim().toLowerCase())))
let sequence=0
watch(()=>[props.topics,route.params.id],async()=>{const current=++sequence;loading.value=true;error.value='';detail.value=null;try{if(route.params.id){const value=await portalApi.navigation(props.topics,route.params.id);if(current===sequence)detail.value=value}else{const value=await(props.topics?portalApi.topics():portalApi.courses());if(current===sequence)items.value=value}}catch(e){if(current===sequence)error.value=e.message}finally{if(current===sequence)loading.value=false}},{immediate:true})
</script>
<template><section class="page-heading heading-row"><div><p class="eyebrow">{{topics?'价值主题与资源组织':'按课程组织教学资源'}}</p><h1>{{detail?`${detail.item.name} · ${topics?'课程思政专题资源':'课程资源'}`:topics?'思政元素专题':'课程资源导航'}}</h1><p class="muted">{{detail?.item.description||(topics?'从课程思政元素进入专题，跨课程查阅已发布资源。':'课程仅展示基本信息及关联资源，不涉及选课、排课或成绩。')}}</p></div><RouterLink v-if="route.params.id" class="secondary" :to="base">返回{{topics?'专题':'课程'}}列表</RouterLink><span v-else class="count-pill">{{loading ? '—' : items.length}} 个{{topics?'专题':'课程'}}</span></section><p v-if="error" class="message error" role="alert">{{error}}</p><LoadingState v-if="loading"/>
<template v-else-if="detail"><section class="card navigation-detail"><span class="file-icon"><AppIcon :name="topics?'tags':'course'" :size="28"/></span><div><h2>{{detail.item.name}}</h2><p>{{detail.item.code||'课程思政元素专题'}} · {{detail.item.resourceCount}} 份已发布资源</p><div class="tag-list"><span class="muted">{{topics?'关联课程':'相关思政元素'}}</span><RouterLink v-for="n in detail.related" :key="n.id" class="tag" :to="`${topics?'/course-resources':'/ideological-topics'}/${n.id}`">{{n.name}} · {{n.resourceCount}}</RouterLink><span v-if="!detail.related.length" class="muted">暂无已发布关联</span></div></div></section><ResourceLibraryView :key="route.fullPath" embedded :fixed-course="topics?undefined:route.params.id" :fixed-element="topics?route.params.id:undefined"/></template>
<template v-else-if="!error"><section class="card navigation-search"><AppIcon name="search"/><input v-model="keyword" :aria-label="topics?'检索专题':'检索课程'" :placeholder="topics?'输入元素名称或说明':'输入课程编号、名称或简介'"/></section><div class="navigation-grid"><RouterLink v-for="n in filtered" :key="n.id" :to="`${base}/${n.id}`" class="navigation-card"><div><span class="file-icon" :class="{ purple:topics }"><AppIcon :name="topics?'tags':'course'" :size="27"/></span><span class="count-pill">{{n.resourceCount}} 份资源</span></div><h2>{{n.name}}</h2><small v-if="n.code">{{n.code}}</small><p class="clamp-3">{{n.description||'暂无说明，可进入查看关联的已发布教学资源。'}}</p><footer>进入{{topics?'专题':'课程'}}<AppIcon name="arrow" :size="17"/></footer></RouterLink></div><EmptyState v-if="!filtered.length" title="暂无符合条件的导航内容" description="这里仅展示启用课程或启用思政元素。"/></template></template>
