<script setup>
import {computed,onMounted,reactive,ref} from 'vue'
import {portalApi} from '../api/portal.js'
import {api} from '../api/client.js'
import {getCourseOptions,getResourceCategoryOptions} from '../api/baseData.js'
import {timeText} from '../api/resourceState.js'
import LoadingState from '../components/LoadingState.vue'
import EmptyState from '../components/EmptyState.vue'
const filters=reactive({keyword:'',courseId:'',categoryId:'',teacherId:''}),courses=ref([]),categories=ref([]),teachers=ref([]),items=ref([]),total=ref(0),page=ref(1),loading=ref(true),error=ref(''),size=10,pages=computed(()=>Math.max(1,Math.ceil(total.value/size)))
let sequence=0
async function load(){const current=++sequence;loading.value=true;error.value='';try{const p={page:page.value,size};for(const[k,v]of Object.entries(filters))if(v)p[k]=v;const r=await portalApi.ledger(p);if(current===sequence){items.value=r.items;total.value=r.total}}catch(e){if(current===sequence)error.value=e.message}finally{if(current===sequence)loading.value=false}}
function search(){page.value=1;load()}
onMounted(async()=>{try{[courses.value,categories.value]=await Promise.all([getCourseOptions(),getResourceCategoryOptions()]);let n=1,r;do{r=await api(`/users?role=TEACHER&page=${n}&size=100`);teachers.value.push(...r.items);n++}while((n-1)*100<r.total)}catch(e){error.value=e.message}await load()})
</script>
<template><section class="page-heading heading-row"><div><p class="eyebrow">管理员 · 只读资源台账</p><h1>已发布资源台账</h1><p class="muted">查看已发布资源的组织信息、使用事件和审核历史，不提供下架或内容编辑。</p></div><span class="count-pill">{{loading ? '—' : total}} 份已发布资源</span></section><section class="card"><form class="filter-row" @submit.prevent="search"><div><label for="ledger-keyword">资源标题</label><input id="ledger-keyword" v-model="filters.keyword" maxlength="200"/></div><div><label for="ledger-course">课程</label><select id="ledger-course" v-model="filters.courseId"><option value="">全部课程</option><option v-for="c in courses" :key="c.id" :value="c.id">{{c.name}}</option></select></div><div><label for="ledger-category">分类</label><select id="ledger-category" v-model="filters.categoryId"><option value="">全部分类</option><option v-for="c in categories" :key="c.id" :value="c.id">{{c.name}}</option></select></div><div><label for="ledger-teacher">教师</label><select id="ledger-teacher" v-model="filters.teacherId"><option value="">全部教师</option><option v-for="t in teachers" :key="t.id" :value="t.id">{{t.displayName}}</option></select></div><button class="primary" :disabled="loading">查询</button></form><p v-if="error" class="message error" role="alert">{{error}}</p><LoadingState v-if="loading"/><div v-else class="table-wrap"><table><thead><tr><th>资源标题 / 思政元素</th><th>课程 / 分类</th><th>教师 / 发布时间</th><th>浏览</th><th>下载</th><th>收藏</th><th>操作</th></tr></thead><tbody><tr v-for="row in items" :key="row.resource.id"><td class="base-name"><strong>{{row.resource.title}}</strong><div class="tag-list"><span class="tag" v-for="e in row.resource.elements" :key="e.id">{{e.name}}</span></div></td><td>{{row.resource.courseName}}<small class="description-cell">{{row.resource.categoryName}}</small></td><td>{{row.resource.teacherName}}<small class="description-cell">{{timeText(row.resource.publishedAt)}}</small></td><td>{{row.usage.browseEvents}}</td><td>{{row.usage.downloadRequests}}</td><td>{{row.usage.currentFavorites}}</td><td><RouterLink class="link-button" :to="`/resource-reviews/${row.resource.id}`">详情与审核历史</RouterLink></td></tr></tbody></table><EmptyState v-if="!items.length" title="暂无符合条件的已发布资源"/></div><div class="pagination"><span>共 {{loading ? '—' : total}} 条 · 第 {{page}} / {{pages}} 页</span><div><button class="secondary" :disabled="page<=1||loading" @click="page--;load()">上一页</button><button class="secondary" :disabled="page>=pages||loading" @click="page++;load()">下一页</button></div></div></section></template>
