<script setup>
import { computed,defineAsyncComponent,onBeforeUnmount,ref,watch } from 'vue'
import { useRoute } from 'vue-router'
import { publishedResourceApi } from '../api/resources.js'
import { portalApi } from '../api/portal.js'
import { timeText } from '../api/resourceState.js'
import AppIcon from '../components/AppIcon.vue'
import LoadingState from '../components/LoadingState.vue'
const PdfPreview=defineAsyncComponent(()=>import('../components/ReviewPdfPreview.vue'))
const route=useRoute(),resource=ref(null),presentation=ref(null),loading=ref(false),busy=ref(false),error=ref(''),previewUrl=ref(''),previewBusy=ref(false)
const canPreview=computed(()=>['application/pdf','image/png','image/jpeg'].includes(resource.value?.fileMimeType)),type=computed(()=>resource.value?.fileOriginalName.split('.').pop().toUpperCase())
let sequence=0,previewSequence=0
function clearPreview(){previewSequence++;if(previewUrl.value)URL.revokeObjectURL(previewUrl.value);previewUrl.value='';previewBusy.value=false}
async function preview(){if(previewBusy.value||!resource.value)return;const current=++previewSequence,id=resource.value.id;previewBusy.value=true;try{const blob=await publishedResourceApi.preview(id);if(current===previewSequence){if(previewUrl.value)URL.revokeObjectURL(previewUrl.value);previewUrl.value=URL.createObjectURL(blob)}}catch(e){if(current===previewSequence)error.value=e.message}finally{if(current===previewSequence)previewBusy.value=false}}
watch(()=>route.params.id,async id=>{const current=++sequence;clearPreview();resource.value=null;presentation.value=null;loading.value=true;error.value='';try{const r=await publishedResourceApi.detail(id);if(current!==sequence)return;resource.value=r;const p=await portalApi.presentation(id);if(current!==sequence)return;presentation.value=p;if(canPreview.value)await preview()}catch(e){if(current===sequence)error.value=e.message}finally{if(current===sequence)loading.value=false}},{immediate:true})
async function favorite(){if(busy.value)return;busy.value=true;const current=sequence,id=resource.value.id;try{const result=await publishedResourceApi.favorite(id,!resource.value.favorite);if(current!==sequence)return;resource.value.favorite=result.favorite;const p=await portalApi.presentation(id);if(current===sequence)presentation.value=p}catch(e){if(current===sequence)error.value=e.message}finally{busy.value=false}}
onBeforeUnmount(()=>{sequence++;clearPreview()})
</script>
<template><p v-if="error" class="message error" role="alert">{{error}}</p><LoadingState v-if="loading" label="正在读取资源与授权预览…"/><template v-if="resource"><section class="page-heading resource-article-head"><p class="eyebrow">教学资源 / 已审核发布</p><h1>{{resource.title}}</h1><div class="tag-list"><RouterLink v-if="resource.courseStatus==='ACTIVE'" class="tag" :to="`/course-resources/${resource.courseId}`">{{resource.courseName}}</RouterLink><span v-else class="tag">{{resource.courseName}}（停用历史课程）</span><span class="category-tag">{{resource.categoryName}}</span><span v-for="e in resource.elements" :key="e.id" class="tag">{{e.name}}</span></div><p class="muted">{{resource.teacherName}} · 发布于 {{timeText(resource.publishedAt)}}</p></section>
<div class="resource-content-grid"><section class="card preview-panel"><div class="section-heading"><h2>资源预览</h2><span class="badge state-APPROVED">{{type}}</span></div><PdfPreview v-if="previewUrl&&resource.fileMimeType==='application/pdf'" :src="previewUrl" label="教学资源"/><img v-else-if="previewUrl" class="review-image" :src="previewUrl" alt="教学资源图片"/><LoadingState v-else-if="previewBusy" label="正在加载附件…"/><div v-else class="file-placeholder"><AppIcon :name="canPreview?'file':'download'" :size="55"/><h3>{{resource.fileOriginalName}}</h3><p>{{canPreview?'预览尚未就绪，可重试读取附件。':'该Office格式暂不支持在线预览，请下载后查看。'}}</p><button v-if="canPreview" class="secondary" @click="preview">重试预览</button><a v-else class="primary" :href="`/api/resources/${resource.id}/download`" :download="resource.fileOriginalName">下载资源</a></div></section>
<aside class="card resource-side"><h2>文件与使用信息</h2><dl><dt>文件名称</dt><dd>{{resource.fileOriginalName}}</dd><dt>类型 / 大小</dt><dd>{{type}} · {{(resource.fileSizeBytes/1024).toFixed(1)}} KiB</dd><dt>发布教师</dt><dd>{{resource.teacherName}}</dd></dl><div v-if="presentation" class="usage-trio"><div><strong>{{presentation.usage.browseEvents}}</strong><span>浏览事件</span></div><div><strong>{{presentation.usage.downloadRequests}}</strong><span>下载请求</span></div><div><strong>{{presentation.usage.currentFavorites}}</strong><span>当前收藏</span></div></div><a class="primary full" :href="`/api/resources/${resource.id}/download`" :download="resource.fileOriginalName"><AppIcon name="download"/>下载资源</a><button class="secondary full" :class="{ 'favorited-button':resource.favorite }" :disabled="busy" @click="favorite"><AppIcon name="favorite"/>{{resource.favorite?'取消收藏':'收藏资源'}}</button><p class="field-hint">浏览为成功打开或刷新详情的访问事件；下载记录不代表文件一定完整保存。</p><RouterLink class="text-button full" to="/resources">返回资源中心</RouterLink></aside></div>
<section class="card content-description"><h2>资源简介</h2><p class="preserve-lines">{{resource.description||'暂无简介。'}}</p></section><div v-if="presentation" class="related-resources"><section v-for="[label,rows] in [['同课程资源',presentation.sameCourse],['相同思政元素资源',presentation.sameElements]]" :key="label"><div class="section-heading"><h2>{{label}}</h2></div><RouterLink v-for="r in rows" :key="r.id" :to="`/resources/${r.id}`" class="inline-resource"><span class="file-icon"><AppIcon name="file"/></span><div><strong>{{r.title}}</strong><small>{{r.courseName}} · {{r.teacherName}}</small></div><AppIcon name="arrow" :size="16"/></RouterLink><p v-if="!rows.length" class="muted">暂无其他关联的已发布资源。</p><p class="field-hint">固定业务关联，不是个性化推荐。</p></section></div></template></template>
