<script setup>
import { computed, ref, reactive, watch, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { publishedResourceApi } from '../api/resources.js'
import { getCourseOptions, getResourceCategoryOptions, getIdeologicalElementOptions } from '../api/baseData.js'
import ResourceCard from '../components/ResourceCard.vue'
import LoadingState from '../components/LoadingState.vue'
import EmptyState from '../components/EmptyState.vue'
import AppIcon from '../components/AppIcon.vue'
const props=defineProps({ favoritesOnly:Boolean, fixedCourse:[String,Number], fixedElement:[String,Number], embedded:Boolean })
const route=useRoute(), filters=reactive({keyword:'',courseId:'',categoryId:'',elementId:''}), courses=ref([]),categories=ref([]),elements=ref([]),items=ref([]),loading=ref(true),error=ref(''),page=ref(1),total=ref(0),changing=ref(0),size=9
const pages=computed(()=>Math.max(1,Math.ceil(total.value/size))), selected=computed(()=>Object.entries(filters).filter(([,v])=>v).map(([key,value])=>({key,label:key==='keyword'?`关键词：${value}`:(key==='courseId'?courses:key==='categoryId'?categories:elements).value.find(x=>String(x.id)===String(value))?.name||value})))
let sequence=0
async function load(){const current=++sequence;loading.value=true;error.value='';try{const params={page:page.value,size};for(const[k,v]of Object.entries(filters))if(String(v).trim())params[k]=String(v).trim();if(props.fixedCourse)params.courseId=props.fixedCourse;if(props.fixedElement)params.elementId=props.fixedElement;const result=await(props.favoritesOnly?publishedResourceApi.favorites({page:page.value,size}):publishedResourceApi.list(params));if(current!==sequence)return;items.value=result.items;total.value=result.total;if(page.value>pages.value){page.value=pages.value;await load()}}catch(e){if(current===sequence)error.value=e.message}finally{if(current===sequence)loading.value=false}}
function search(){page.value=1;load()}function reset(){Object.assign(filters,{keyword:'',courseId:'',categoryId:'',elementId:''});search()}
async function favorite(r){if(changing.value)return;changing.value=r.id;try{r.favorite=(await publishedResourceApi.favorite(r.id,!r.favorite)).favorite;if(props.favoritesOnly)await load()}catch(e){error.value=e.message}finally{changing.value=0}}
watch(()=>[props.favoritesOnly,props.fixedCourse,props.fixedElement],search)
watch(()=>route.query,query=>{if(props.embedded)return;Object.assign(filters,{keyword:String(query.keyword||''),courseId:String(query.courseId||''),categoryId:String(query.categoryId||''),elementId:String(query.elementId||'')});search()},{immediate:true})
onMounted(async()=>{try{[courses.value,categories.value,elements.value]=await Promise.all([getCourseOptions(),getResourceCategoryOptions(),getIdeologicalElementOptions()])}catch(e){error.value=e.message}if(props.embedded)await load()})
</script>
<template><section v-if="!embedded" class="page-heading heading-row"><div><p class="eyebrow">资源发现与内部共享</p><h1>{{favoritesOnly?'我的收藏':'资源中心'}}</h1><p class="muted">{{favoritesOnly?'已收藏且当前仍已发布的教学资源，便于持续查阅。':'按课程、分类和课程思政元素发现已审核发布的教学资源。'}}</p></div><span class="count-pill">{{loading ? '—' : total}} 份资源</span></section>
<section v-if="!favoritesOnly" class="card filter-card"><form class="filter-row" @submit.prevent="search"><div><label for="library-keyword">关键词</label><input id="library-keyword" v-model="filters.keyword" placeholder="资源标题或简介" maxlength="200"/></div><div v-if="!fixedCourse"><label for="library-course">课程</label><select id="library-course" v-model="filters.courseId"><option value="">全部课程</option><option v-for="c in courses" :key="c.id" :value="c.id">{{c.name}}</option></select></div><div><label for="library-category">资源分类</label><select id="library-category" v-model="filters.categoryId"><option value="">全部分类</option><option v-for="c in categories" :key="c.id" :value="c.id">{{c.name}}</option></select></div><div v-if="!fixedElement"><label for="library-element">课程思政元素</label><select id="library-element" v-model="filters.elementId"><option value="">全部元素</option><option v-for="e in elements" :key="e.id" :value="e.id">{{e.name}}</option></select></div><button class="primary" :disabled="loading"><AppIcon name="search" :size="17"/>查询</button><button type="button" class="secondary" @click="reset">重置</button></form><div v-if="selected.length" class="tag-list filter-tags"><span>当前筛选</span><button v-for="tag in selected" :key="tag.key" class="tag" @click="filters[tag.key]='';search()">{{tag.label}}<AppIcon name="close" :size="13"/></button></div></section>
<p v-if="error" class="message error" role="alert">{{error}}</p><LoadingState v-if="loading"/><div v-else class="resource-card-grid"><ResourceCard v-for="r in items" :key="r.id" :resource="r" :changing="!!changing" @favorite="favorite"/></div><EmptyState v-if="!loading&&!items.length" :title="favoritesOnly?'暂无有效收藏':'没有符合条件的资源'" :description="favoritesOnly?'在资源中心收藏已发布资源后，可在这里快速访问。':'请调整或重置筛选条件，未审核资源不会出现在这里。'"/>
<div class="pagination"><span>共 {{loading ? '—' : total}} 条 · 第 {{page}} / {{pages}} 页</span><div><button class="secondary" :disabled="loading||page<=1" @click="page--;load()">上一页</button><button class="secondary" :disabled="loading||page>=pages" @click="page++;load()">下一页</button></div></div></template>
